Paramaters:
   MyUser:
    Type: String
    Default: username1
   CTXPassWord:
    Type: String
    Default: Rajeshsr4
Resources:
  IAMUserName:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        - Password: !Ref CTXPassWord
        - UserName: !Ref MyUser
    Properties:
       Policies:
       - PolicyName: giveaccesstoqueueonly
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
             - Effect: Allow
               Action:
                - s3:Get*
               Resource: "*"